#!/bin/sh
/bin/mknod  -m666 /dev/ttys0 c 4 64
/bin/mknod  -m666 /dev/ttyAMA0 c 204 64
/bin/mknod  -m666 /dev/fb0 c 29 0
/bin/1
/bin/2
/bin/3

var=0
flag=100000
while true
	do
		let var=$var+1
		if [ "$var" -eq "$flag" ];
		then
			let var=0
			echo "Hello,my dear TA!"
		fi
	done

